### ISSUE TITLE
Make A Footer

### ISSUE THREAD

**Issue by Mohak1809** [Mohak1809/PortFolio-Website#3]
The footer consist of Contact Me components such as input entries for name email and contact number

**Comment by rajveerpathak1** [comment]
@Mohak1809 please assign this issue to me.

**Comment by Mohak1809** [comment]
@rajveerpathak1 okay

**Comment by Mohak1809** [comment]
@rajveerpathak1 bro perform all the work on a separate branch and sent pull req through that branch.

**Comment by jaiyankargupta** [comment]
merged this issue
